server:
  port: 8080

spring:
  application:
    name: bugtrackercli
  security:
    oauth2:
      client:
        registration:
          bugstat:
            provider: keycloak
            client-name: bugstats
            client-id: bugtracker-stats
            client-secret: 8sSc2emoNhXjYiiDklvMERUFYbzz1rFQ
            authorization-grant-type: client_credentials
          keycloak-oidc:
            provider: keycloak
            client-name: Keycloak
            client-id: bugtracker
            # Uncomment the following line if you have a client secret
            client-secret: ${CLIENT_SECRET}
            # client-authentication-method: none # If you are using PCKE and you have a public client
            authorization-grant-type: authorization_code
            # scope: openid,profile,email,bugtracker
            scope: openid,profile,email
          gitlab-oauth:
            provider: gitlab
            client-name: GitLab
            client-id: ${GITLAB_CLIENT_ID}
            client-secret: ${GITLAB_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: read_user,api,read_api
#          gitlab-oidc:
#            provider: gitlab
#            client-name: GitLab
#            client-id: ${GITLAB_CLIENT_ID}
#            client-secret: ${GITLAB_CLIENT_SECRET}
#            authorization-grant-type: authorization_code
#            scope: openid,profile,email

        provider:
          keycloak:
            issuer-uri: http://127.0.0.1:9090/realms/oauthrealm
          gitlab:
            issuer-uri: https://gitlab.com


logging:
  level:
    web: TRACE
    org:
      springframework:
        web:
          client: TRACE

bugtracker:
  api:
    url: http://localhost:8081/bugtrackerapi

gitlab:
  api:
    url: https://gitlab.com/api/v4


## GitLab specific OAuth 2 related properties
#spring.security.oauth2.client.registration.gitlab-oidc.provider=gitlab
#spring.security.oauth2.client.registration.gitlab-oidc.client-name=GitLab
#spring.security.oauth2.client.registration.gitlab-oidc.client-id=<<GitLab Client Id>>
#spring.security.oauth2.client.registration.gitlab-oidc.client-secret=<<Gitlab Client secret>>
#spring.security.oauth2.client.registration.gitlab-oidc.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.gitlab-oidc.scope=openid,profile,email

### You need to set the issuer (Not Strictly Required because its already known to Spring Boot)
## Openid configuration - https://gitlab.com/.well-known/openid-configuration
#spring.security.oauth2.client.provider.gitlab.issuer-uri=https://gitlab.com

